version: "3.3"
services:

  # a app script
  # app:
  #   build:
  #     context: app
  #   stop_signal: SIGKILL
  #   ports:
  #     - 5000:5000

  metrics-api:
    build:
      context: metrics-api
    stop_signal: SIGKILL
    ports:
      - 8080:8080
    links:
      - grafana

  # random load generator
  generator:
    build:
      context: generator
    stop_signal: SIGKILL
    links:
      - metrics-api

  prometheus:
    build: ./prometheus/
    ports:
      - "9090:9090"

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
    links:
      - prometheus
