version: "3.3"
services:

  # a app script
  app:
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - 5000:5000

  prometheus:
    build: ./prometheus/
    ports:
      - "9090:9090"