global:
  scrape_interval:     3s

  external_labels:
      monitor: 'example-app'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'efficient_metrics'

    dns_sd_configs:
      - names: ['app']
        port: 5000
        type: A
        refresh_interval: 5s
  - job_name: 'metrics-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s                  
    static_configs:                       
      - targets: ['localhost:8083']