apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123